# Generated by Django 4.0.5 on 2022-12-24 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ca', models.CharField(max_length=50)),
                ('ca_rep', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cp', models.CharField(max_length=50)),
                ('cp_rep', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Exang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exang', models.CharField(max_length=50)),
                ('exang_rep', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Fbs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fbs', models.CharField(max_length=50)),
                ('fbs_rep', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Restecg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restecg', models.CharField(max_length=50)),
                ('restecg_rep', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(max_length=50)),
                ('sex_rep', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Slope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slope', models.CharField(max_length=50)),
                ('slope_rep', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Thal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thal', models.CharField(max_length=50)),
                ('thal_rep', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('age', models.SmallIntegerField()),
                ('trestbps', models.SmallIntegerField()),
                ('chol', models.SmallIntegerField()),
                ('thalach', models.SmallIntegerField()),
                ('oldpeak', models.FloatField()),
                ('target', models.CharField(max_length=50)),
                ('ca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.ca')),
                ('cp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.cp')),
                ('exang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.exang')),
                ('fbs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.fbs')),
                ('restecg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.restecg')),
                ('sex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.sex')),
                ('slope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.slope')),
                ('thal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.thal')),
            ],
        ),
    ]
