# Generated by Django 4.1.4 on 2023-01-10 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=200)),
                ("surname", models.CharField(max_length=200)),
                ("age", models.SmallIntegerField()),
                ("sex", models.CharField(max_length=50)),
                ("cp", models.CharField(max_length=50)),
                ("trestbps", models.SmallIntegerField()),
                ("chol", models.SmallIntegerField()),
                ("fbs", models.CharField(max_length=50)),
                ("restecg", models.CharField(max_length=50)),
                ("thalach", models.SmallIntegerField()),
                ("exang", models.CharField(max_length=50)),
                ("oldpeak", models.FloatField()),
                ("slope", models.CharField(max_length=50)),
                ("ca", models.CharField(max_length=50)),
                ("thal", models.CharField(max_length=50)),
                ("target", models.CharField(max_length=50)),
            ],
        ),
    ]
