# Generated by Django 4.0.5 on 2022-12-24 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_remove_ca_ca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ca',
            name='ca_rep',
            field=models.CharField(max_length=10),
        ),
    ]
