# Generated by Django 4.1.4 on 2022-12-26 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0003_alter_ca_ca_rep"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="ca",
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name="patient",
            name="cp",
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name="patient",
            name="exang",
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name="patient",
            name="fbs",
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name="patient",
            name="restecg",
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name="patient",
            name="sex",
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name="patient",
            name="slope",
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name="patient",
            name="thal",
            field=models.SmallIntegerField(),
        ),
        migrations.DeleteModel(
            name="Ca",
        ),
        migrations.DeleteModel(
            name="Cp",
        ),
        migrations.DeleteModel(
            name="Exang",
        ),
        migrations.DeleteModel(
            name="Fbs",
        ),
        migrations.DeleteModel(
            name="Restecg",
        ),
        migrations.DeleteModel(
            name="Sex",
        ),
        migrations.DeleteModel(
            name="Slope",
        ),
        migrations.DeleteModel(
            name="Thal",
        ),
    ]
