# Generated by Django 4.1.4 on 2022-12-26 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0004_alter_patient_ca_alter_patient_cp_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="cp",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="patient",
            name="exang",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="patient",
            name="fbs",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="patient",
            name="restecg",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="patient",
            name="sex",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="patient",
            name="slope",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="patient",
            name="thal",
            field=models.CharField(max_length=50),
        ),
    ]
